version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql-testing
    volumes:
      - .:/work

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/work
    depends_on:
      - php
    ports:
      - 80:80

  php-cli:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    depends_on:
      - mysql-testing
    volumes:
      - .:/work

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/work

  mysql-testing:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testing-db
      - MYSQL_USER=testing
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "13306:3306"
    volumes:
      - database-testing:/var/lib/mysql

volumes:
  database-testing:
