name: CI Code Analysis
on:
  - pull_request
jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: echo 'lint'
