name: CI - Code Analysis
on: pull_request
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          ini-values: date.timezone=Asia/Tokyo, mbstring.language=Japanese
          tools: composer:v2, cs2pr
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml --report=checkstyle -q | cs2pr
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          ini-values: date.timezone=Asia/Tokyo, mbstring.language=Japanese
          tools: composer:v2, cs2pr
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: PHPStan
        run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
